name: paul-numpy-example
version: git
summary: paul-numpy-example
description: A snapped numpy example
grade: devel
confinement: devmode

apps:
  paul-numpy-example:
    command: main

parts:
  paul-numpy-example:
    plugin: python
    python-version: python3
    requirements: ./requirements.txt
    source: .
    source-type: git